In [4]:
import pandas as pd

In [14]:
df=pd.read_csv("data.csv")

In [15]:
df.head()

Fever  Body Pain  Age  Runny Nose  Diff Breathe  Infection
0     99          1   21           0             0          1
1     98          1   94           1             1          1
2     99          1   62           0            -1          0
3    105          1   74           0            -1          0
4    101          1   15           1            -1          1

In [16]:
df.tail()

Fever  Body Pain  Age  Runny Nose  Diff Breathe  Infection
2469    107          1   87           0            -1          0
2470    103          1   72           0            -1          0
2471     98          1   32           0            -1          0
2472    105          1   62           1             1          1
2473    106          1   33           1             1          0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2474 entries, 0 to 2473
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Fever         2474 non-null   int64
 1   Body Pain     2474 non-null   int64
 2   Age           2474 non-null   int64
 3   Runny Nose    2474 non-null   int64
 4   Diff Breathe  2474 non-null   int64
 5   Infection     2474 non-null   int64
dtypes: int64(6)
memory usage: 116.0 KB


In [18]:
df["Fever"].value_counts()

98     208
107    196
109    190
103    182
102    181
100    180
97     178
110    178
108    175
105    174
104    168
106    161
101    153
99     150
Name: Fever, dtype: int64

In [19]:
df.describe()

Fever    Body Pain          Age   Runny Nose  Diff Breathe  \
count  2474.000000  2474.000000  2474.000000  2474.000000   2474.000000   
mean    103.529103     0.497575    50.612369     0.516572     -0.010105   
std       4.077415     0.500095    28.825796     0.499826      0.818989   
min      97.000000     0.000000     1.000000     0.000000     -1.000000   
25%     100.000000     0.000000    26.000000     0.000000     -1.000000   
50%     104.000000     0.000000    50.000000     1.000000      0.000000   
75%     107.000000     1.000000    75.000000     1.000000      1.000000   
max     110.000000     1.000000   100.000000     1.000000      1.000000   

         Infection  
count  2474.000000  
mean      0.506871  
std       0.500054  
min       0.000000  
25%       0.000000  
50%       1.000000  
75%       1.000000  
max       1.000000

## Train Test Splitting

In [20]:
import numpy as np

In [21]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled=np.random.permutation(len(data))
    test_set_size=int(len(data)*ratio)                               
    test_indices=shuffled[:test_set_size]
    train_indices=shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [22]:
train, test=data_split(df, 0.2)

In [23]:
train

Fever  Body Pain  Age  Runny Nose  Diff Breathe  Infection
76      110          0   14           1             0          1
2090    102          1   29           1            -1          1
1451     97          1   56           1             0          1
2137     99          0   12           1             1          0
969     105          0    5           0             1          1
...     ...        ...  ...         ...           ...        ...
1638    106          0   83           0            -1          1
1095    110          0   29           0             1          1
1130    109          0   89           1             0          0
1294    102          1   48           1            -1          1
860      98          0   29           1             0          0

[1980 rows x 6 columns]

In [34]:
test

Fever  Body Pain  Age  Runny Nose  Diff Breathe  Infection
873     109          0   45           0             0          0
2037    101          1   82           1             0          0
952     102          0   84           0             0          1
1615    103          1   46           0             0          0
1712    101          1   64           1             0          1
...     ...        ...  ...         ...           ...        ...
1310    104          0   93           0            -1          0
867     100          0   95           0             1          0
1361    105          1   46           0             1          1
2404    107          1   15           0            -1          1
651     103          1   20           1            -1          1

[494 rows x 6 columns]

In [45]:
x_train=train[["Fever", "Body Pain", "Age", "Runny Nose", "Diff Breathe"]].to_numpy()
x_test=test[["Fever", "Body Pain", "Age", "Runny Nose", "Diff Breathe"]].to_numpy()


In [46]:
y_train=train[["Infection"]].to_numpy().reshape(1980 ,)
y_test=test[["Infection"]].to_numpy().reshape(494 ,)
y_train

array([1, 1, 1, ..., 0, 1, 0], dtype=int64)

In [38]:
from sklearn.linear_model import LogisticRegression

In [47]:
clf=LogisticRegression()
clf.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [48]:
y_test

array([0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,

## yes or no

In [53]:
clf.predict([[97, 0, 2, 0, 0]])

array([1], dtype=int64)

##proba

In [60]:
inputFeatures=[97, 0, 10, 0, 1]
Infection=clf.predict_proba([inputFeatures])[0][1]

In [58]:
Infection

0.5119671664021361

In [61]:
Infection

0.5319044335226706